remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

title: Moving Mountains
description：My life

read_time: true
words_per_minute: 200

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
