remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

title: Moving Mountains
name: "Siyuan Gong"
# url: "https://sygong.github.io"
repository: "SYGong/sygong.github.io"
author: Siyuan Gong

markdown: kramdown
mathjax: true
# kramdown:
#  math_engine: mathjax
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author: Siyuan Gong
      author_profile: true
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author: Siyuan Gong
      author_profile: true
      share: true
      
date_format: "%B %-d, %Y"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
paginate: 5

sidebar: true
search: true

ga_track_id: 'UA-129240192-1'
ga_domain: auto
