remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "sunrise"

title: Moving Mountains
description：My life
locate: "zh-CN"
url: "https://sygong.github.io"
repository: "SYGong/sygong.github.io"

read_time: true
words_per_minute: 200

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Siyuan Gong"
  bio: "Hunting"
  location: "Somewhere"
