remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

title: Moving Mountains
name: "Siyuan Gong"
# url: "https://sygong.github.io"
repository: "SYGong/sygong.github.io"
author: Siyuan Gong

markdown: kramdown
mathjax: true
# kramdown:
#  math_engine: mathjax
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author: Siyuan Gong
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author: Siyuan Gong
      author_profile: true
      share: true
      
date_format: "%B %-d, %Y"

teaser: /assets/images/teaser.png

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
# permalink: /blog/:categories/:year/:month/:day/:title/

paginate: 5
paginate_path: /blog/page:num/

sidebar: true
search: true

ga_track_id: 'UA-129240192-1'
ga_domain: auto

comments:
  provider: "facebook"
  facebook:
    num_posts: 5
    colorscheme: "light"
