remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

title: Moving Mountains
name: "Siyuan Gong"
url: "https://sygong.github.io"
repository: "SYGong/sygong.github.io"

# read_time: true
# words_per_minute: 200

markdown: kramdown
mathjax: true
# kramdown:
#  math_engine: mathjax
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
paginate: 5

author:
  name: "Siyuan Gong"
  bio: "Hunting"
  location: "Somewhere"

sidebar: true
